version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel
        ports:
            - "9000:9000"

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./site.conf:/etc/nginx/conf.d/site.conf
        networks:
            - laravel

    # db mysql
    db:
        image: mysql:latest
        container_name: mysql-control
        ports:
        - 3309:3306
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cosmos
            MYSQL_USER: william
            MYSQL_PASSWORD: william
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
