version: "3.7"

services:
    # nginx
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/www
            # - ./sites.conf:/etc/nginx/conf.d/site.conf
            - ./sites.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        links:
            - app
        depends_on:
            - app

    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: app
        volumes:
            - ./:/www
        networks:
            - laravel
        ports:
            - "9000:9000"
        # command: php artisan migrate
        depends_on:
            - mysql-control
            - db
    # db mysql
    db:
        image: mysql:latest
        container_name: mysql-control
        ports:
        - 3308:3306
        restart: unless-stopped
        volumes:
          - ./storage/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cosmos
            MYSQL_USER: william
            MYSQL_PASSWORD: william
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
